GET http://localhost:8888/.netlify/functions/hello

###

GET http://localhost:8888/.netlify/functions/getClients

###

GET http://localhost:8888/.netlify/functions/getClientById?id=5

###

POST http://localhost:8888/.netlify/functions/addClient
Content-Type: application/json

{
  "name": "testName1",
  "surname": "testSurname1",
  "phone": "123456789",
  "interests": ["tech"]
}

###

PUT http://localhost:8888/.netlify/functions/updateClient?id=5
Content-Type: application/json

{
  "name": "Anna",
  "surname": "Nowak",
  "phone": 11223344,
  "interests": ["music", "sport"]
}

###

DELETE http://localhost:8888/.netlify/functions/deleteClient?id=4

###
